import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      "xs": "400px",
      "sm": "640px",
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--on-primary))",
          container: "hsl(var(--primary-container))",
          "on-container": "hsl(var(--on-primary-container))",
        },
        secondary: {
          DEFAULT: "#4a6729",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        "secondary-container": "#c9eb9e",
        "surface-dim": "hsl(var(--surface-dim))",
        "surface-bright": "hsl(var(--surface-bright))",
        "on-secondary-fixed": "#102000",
        "error-container": "#ffdad6",
        "inverse-primary": "#96d945",
        "surface-variant": "hsl(var(--surface-container-high))",
        "surface": "hsl(var(--surface))",
        "primary-fixed-dim": "#96d945",
        "on-background": "hsl(var(--on-surface))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "tertiary": "#6d5b52",
        "secondary-fixed-dim": "#b0d187",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "inverse-on-surface": "#f1effc",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#102000",
        "error": "#ba1a1a",
        "on-primary-container": "hsl(var(--on-primary-container))",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#2e4f00",
        "on-surface": "hsl(var(--on-surface))",
        "on-secondary-container": "#4f6b2d",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "on-primary": "hsl(var(--on-primary))",
        "primary-container": "hsl(var(--primary-container))",
        "surface-container": "hsl(var(--surface-container))",
        "on-error-container": "#93000a",
        "tertiary-container": "#ffe6da",
        "tertiary-fixed-dim": "#d9c2b6",
        "secondary-fixed": "#cceea1",
        "on-secondary-fixed-variant": "#344e13",
        "primary-fixed": "#b1f65f",
        "on-error": "#ffffff",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "surface-tint": "hsl(var(--primary))",
        "outline": "hsl(var(--outline))",
        "on-tertiary-fixed": "#251912",
        "on-tertiary-fixed-variant": "#54433b",
        "on-tertiary-container": "#78665c",
        "outline-variant": "hsl(var(--outline-variant))",
        "inverse-surface": "#2f3039",
        "tertiary-fixed": "#f6ded2",
        green: {
          DEFAULT: "#B9FF66",
          light: "#C7FF85",
          dark: "#A8E855",
        },
        brand: {
          green: "#B9FF66",
          dark: "#191A23",
        },
        gray: {
          subtle: "#686363",
        },
        slate: {
          900: "#0F172A",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.125rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"]
      },
      boxShadow: {
        brand: "0px 5px 0px #191A23",
        "brand-lg": "0px 8px 0px #191A23",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;